#!/bin/bash

KEYWORD=$1
ORGANIZATION=$2
GITHUB_HOME=~/ghq/github.com

LIST=$(curl --silent -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${GITHUB_TOKEN}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/search/code?q=${KEYWORD}+org:${ORGANIZATION}" | jq -r '.items[].html_url' | fzf --reverse --exact)

if [ -n "${LIST}" ]; then
  ARGS=(${LIST//\// })
  DIR="${GITHUB_HOME}/${ARGS[2]}/${ARGS[3]}"
  cd ${DIR}
  exec /bin/zsh
fi
